/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TwoFactorRouteImport } from './routes/two-factor'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as Setup2faRouteImport } from './routes/setup-2fa'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthDashboardWatchlistRouteImport } from './routes/_auth/dashboard_.watchlist'
import { Route as AuthDashboardTemplatesRouteImport } from './routes/_auth/dashboard_.templates'
import { Route as AuthDashboardTaxRouteImport } from './routes/_auth/dashboard_.tax'
import { Route as AuthDashboardStrategiesRouteImport } from './routes/_auth/dashboard_.strategies'
import { Route as AuthDashboardSettingsRouteImport } from './routes/_auth/dashboard_.settings'
import { Route as AuthDashboardScreenerRouteImport } from './routes/_auth/dashboard_.screener'
import { Route as AuthDashboardResearchRouteImport } from './routes/_auth/dashboard_.research'
import { Route as AuthDashboardRatesRouteImport } from './routes/_auth/dashboard_.rates'
import { Route as AuthDashboardPortfoliosRouteImport } from './routes/_auth/dashboard_.portfolios'
import { Route as AuthDashboardNewsRouteImport } from './routes/_auth/dashboard_.news'
import { Route as AuthDashboardMyLearningRouteImport } from './routes/_auth/dashboard_.my-learning'
import { Route as AuthDashboardLearnTaRouteImport } from './routes/_auth/dashboard_.learn-ta'
import { Route as AuthDashboardLearnRatesRouteImport } from './routes/_auth/dashboard_.learn-rates'
import { Route as AuthDashboardLearnInvestmentRouteImport } from './routes/_auth/dashboard_.learn-investment'
import { Route as AuthDashboardLearnFeesRouteImport } from './routes/_auth/dashboard_.learn-fees'
import { Route as AuthDashboardLearnBuySellRouteImport } from './routes/_auth/dashboard_.learn-buy-sell'
import { Route as AuthDashboardIndicesRouteImport } from './routes/_auth/dashboard_.indices'
import { Route as AuthDashboardCryptoRouteImport } from './routes/_auth/dashboard_.crypto'
import { Route as AuthDashboardComparisonRouteImport } from './routes/_auth/dashboard_.comparison'
import { Route as AuthDashboardCommoditiesRouteImport } from './routes/_auth/dashboard_.commodities'
import { Route as AuthDashboardCalendarRouteImport } from './routes/_auth/dashboard_.calendar'
import { Route as AuthDashboardBacktestRouteImport } from './routes/_auth/dashboard_.backtest'
import { Route as AuthDashboardAnalysisRouteImport } from './routes/_auth/dashboard_.analysis'
import { Route as AuthDashboardAlertsRouteImport } from './routes/_auth/dashboard_.alerts'
import { Route as AuthDashboardAdvisorRouteImport } from './routes/_auth/dashboard_.advisor'
import { Route as AuthDashboardPortfoliosPortfolioIdRouteImport } from './routes/_auth/dashboard_.portfolios_.$portfolioId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TwoFactorRoute = TwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const Setup2faRoute = Setup2faRouteImport.update({
  id: '/setup-2fa',
  path: '/setup-2fa',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardWatchlistRoute = AuthDashboardWatchlistRouteImport.update({
  id: '/dashboard_/watchlist',
  path: '/dashboard/watchlist',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardTemplatesRoute = AuthDashboardTemplatesRouteImport.update({
  id: '/dashboard_/templates',
  path: '/dashboard/templates',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardTaxRoute = AuthDashboardTaxRouteImport.update({
  id: '/dashboard_/tax',
  path: '/dashboard/tax',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardStrategiesRoute = AuthDashboardStrategiesRouteImport.update({
  id: '/dashboard_/strategies',
  path: '/dashboard/strategies',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardSettingsRoute = AuthDashboardSettingsRouteImport.update({
  id: '/dashboard_/settings',
  path: '/dashboard/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardScreenerRoute = AuthDashboardScreenerRouteImport.update({
  id: '/dashboard_/screener',
  path: '/dashboard/screener',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardResearchRoute = AuthDashboardResearchRouteImport.update({
  id: '/dashboard_/research',
  path: '/dashboard/research',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRatesRoute = AuthDashboardRatesRouteImport.update({
  id: '/dashboard_/rates',
  path: '/dashboard/rates',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardPortfoliosRoute = AuthDashboardPortfoliosRouteImport.update({
  id: '/dashboard_/portfolios',
  path: '/dashboard/portfolios',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardNewsRoute = AuthDashboardNewsRouteImport.update({
  id: '/dashboard_/news',
  path: '/dashboard/news',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardMyLearningRoute = AuthDashboardMyLearningRouteImport.update({
  id: '/dashboard_/my-learning',
  path: '/dashboard/my-learning',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardLearnTaRoute = AuthDashboardLearnTaRouteImport.update({
  id: '/dashboard_/learn-ta',
  path: '/dashboard/learn-ta',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardLearnRatesRoute = AuthDashboardLearnRatesRouteImport.update({
  id: '/dashboard_/learn-rates',
  path: '/dashboard/learn-rates',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardLearnInvestmentRoute =
  AuthDashboardLearnInvestmentRouteImport.update({
    id: '/dashboard_/learn-investment',
    path: '/dashboard/learn-investment',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthDashboardLearnFeesRoute = AuthDashboardLearnFeesRouteImport.update({
  id: '/dashboard_/learn-fees',
  path: '/dashboard/learn-fees',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardLearnBuySellRoute =
  AuthDashboardLearnBuySellRouteImport.update({
    id: '/dashboard_/learn-buy-sell',
    path: '/dashboard/learn-buy-sell',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthDashboardIndicesRoute = AuthDashboardIndicesRouteImport.update({
  id: '/dashboard_/indices',
  path: '/dashboard/indices',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardCryptoRoute = AuthDashboardCryptoRouteImport.update({
  id: '/dashboard_/crypto',
  path: '/dashboard/crypto',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardComparisonRoute = AuthDashboardComparisonRouteImport.update({
  id: '/dashboard_/comparison',
  path: '/dashboard/comparison',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardCommoditiesRoute =
  AuthDashboardCommoditiesRouteImport.update({
    id: '/dashboard_/commodities',
    path: '/dashboard/commodities',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthDashboardCalendarRoute = AuthDashboardCalendarRouteImport.update({
  id: '/dashboard_/calendar',
  path: '/dashboard/calendar',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardBacktestRoute = AuthDashboardBacktestRouteImport.update({
  id: '/dashboard_/backtest',
  path: '/dashboard/backtest',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardAnalysisRoute = AuthDashboardAnalysisRouteImport.update({
  id: '/dashboard_/analysis',
  path: '/dashboard/analysis',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardAlertsRoute = AuthDashboardAlertsRouteImport.update({
  id: '/dashboard_/alerts',
  path: '/dashboard/alerts',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardAdvisorRoute = AuthDashboardAdvisorRouteImport.update({
  id: '/dashboard_/advisor',
  path: '/dashboard/advisor',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardPortfoliosPortfolioIdRoute =
  AuthDashboardPortfoliosPortfolioIdRouteImport.update({
    id: '/dashboard_/portfolios_/$portfolioId',
    path: '/dashboard/portfolios/$portfolioId',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup-2fa': typeof Setup2faRoute
  '/sign-up': typeof SignUpRoute
  '/two-factor': typeof TwoFactorRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof AuthDashboardRoute
  '/dashboard/advisor': typeof AuthDashboardAdvisorRoute
  '/dashboard/alerts': typeof AuthDashboardAlertsRoute
  '/dashboard/analysis': typeof AuthDashboardAnalysisRoute
  '/dashboard/backtest': typeof AuthDashboardBacktestRoute
  '/dashboard/calendar': typeof AuthDashboardCalendarRoute
  '/dashboard/commodities': typeof AuthDashboardCommoditiesRoute
  '/dashboard/comparison': typeof AuthDashboardComparisonRoute
  '/dashboard/crypto': typeof AuthDashboardCryptoRoute
  '/dashboard/indices': typeof AuthDashboardIndicesRoute
  '/dashboard/learn-buy-sell': typeof AuthDashboardLearnBuySellRoute
  '/dashboard/learn-fees': typeof AuthDashboardLearnFeesRoute
  '/dashboard/learn-investment': typeof AuthDashboardLearnInvestmentRoute
  '/dashboard/learn-rates': typeof AuthDashboardLearnRatesRoute
  '/dashboard/learn-ta': typeof AuthDashboardLearnTaRoute
  '/dashboard/my-learning': typeof AuthDashboardMyLearningRoute
  '/dashboard/news': typeof AuthDashboardNewsRoute
  '/dashboard/portfolios': typeof AuthDashboardPortfoliosRoute
  '/dashboard/rates': typeof AuthDashboardRatesRoute
  '/dashboard/research': typeof AuthDashboardResearchRoute
  '/dashboard/screener': typeof AuthDashboardScreenerRoute
  '/dashboard/settings': typeof AuthDashboardSettingsRoute
  '/dashboard/strategies': typeof AuthDashboardStrategiesRoute
  '/dashboard/tax': typeof AuthDashboardTaxRoute
  '/dashboard/templates': typeof AuthDashboardTemplatesRoute
  '/dashboard/watchlist': typeof AuthDashboardWatchlistRoute
  '/dashboard/portfolios/$portfolioId': typeof AuthDashboardPortfoliosPortfolioIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup-2fa': typeof Setup2faRoute
  '/sign-up': typeof SignUpRoute
  '/two-factor': typeof TwoFactorRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof AuthDashboardRoute
  '/dashboard/advisor': typeof AuthDashboardAdvisorRoute
  '/dashboard/alerts': typeof AuthDashboardAlertsRoute
  '/dashboard/analysis': typeof AuthDashboardAnalysisRoute
  '/dashboard/backtest': typeof AuthDashboardBacktestRoute
  '/dashboard/calendar': typeof AuthDashboardCalendarRoute
  '/dashboard/commodities': typeof AuthDashboardCommoditiesRoute
  '/dashboard/comparison': typeof AuthDashboardComparisonRoute
  '/dashboard/crypto': typeof AuthDashboardCryptoRoute
  '/dashboard/indices': typeof AuthDashboardIndicesRoute
  '/dashboard/learn-buy-sell': typeof AuthDashboardLearnBuySellRoute
  '/dashboard/learn-fees': typeof AuthDashboardLearnFeesRoute
  '/dashboard/learn-investment': typeof AuthDashboardLearnInvestmentRoute
  '/dashboard/learn-rates': typeof AuthDashboardLearnRatesRoute
  '/dashboard/learn-ta': typeof AuthDashboardLearnTaRoute
  '/dashboard/my-learning': typeof AuthDashboardMyLearningRoute
  '/dashboard/news': typeof AuthDashboardNewsRoute
  '/dashboard/portfolios': typeof AuthDashboardPortfoliosRoute
  '/dashboard/rates': typeof AuthDashboardRatesRoute
  '/dashboard/research': typeof AuthDashboardResearchRoute
  '/dashboard/screener': typeof AuthDashboardScreenerRoute
  '/dashboard/settings': typeof AuthDashboardSettingsRoute
  '/dashboard/strategies': typeof AuthDashboardStrategiesRoute
  '/dashboard/tax': typeof AuthDashboardTaxRoute
  '/dashboard/templates': typeof AuthDashboardTemplatesRoute
  '/dashboard/watchlist': typeof AuthDashboardWatchlistRoute
  '/dashboard/portfolios/$portfolioId': typeof AuthDashboardPortfoliosPortfolioIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/setup-2fa': typeof Setup2faRoute
  '/sign-up': typeof SignUpRoute
  '/two-factor': typeof TwoFactorRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/dashboard_/advisor': typeof AuthDashboardAdvisorRoute
  '/_auth/dashboard_/alerts': typeof AuthDashboardAlertsRoute
  '/_auth/dashboard_/analysis': typeof AuthDashboardAnalysisRoute
  '/_auth/dashboard_/backtest': typeof AuthDashboardBacktestRoute
  '/_auth/dashboard_/calendar': typeof AuthDashboardCalendarRoute
  '/_auth/dashboard_/commodities': typeof AuthDashboardCommoditiesRoute
  '/_auth/dashboard_/comparison': typeof AuthDashboardComparisonRoute
  '/_auth/dashboard_/crypto': typeof AuthDashboardCryptoRoute
  '/_auth/dashboard_/indices': typeof AuthDashboardIndicesRoute
  '/_auth/dashboard_/learn-buy-sell': typeof AuthDashboardLearnBuySellRoute
  '/_auth/dashboard_/learn-fees': typeof AuthDashboardLearnFeesRoute
  '/_auth/dashboard_/learn-investment': typeof AuthDashboardLearnInvestmentRoute
  '/_auth/dashboard_/learn-rates': typeof AuthDashboardLearnRatesRoute
  '/_auth/dashboard_/learn-ta': typeof AuthDashboardLearnTaRoute
  '/_auth/dashboard_/my-learning': typeof AuthDashboardMyLearningRoute
  '/_auth/dashboard_/news': typeof AuthDashboardNewsRoute
  '/_auth/dashboard_/portfolios': typeof AuthDashboardPortfoliosRoute
  '/_auth/dashboard_/rates': typeof AuthDashboardRatesRoute
  '/_auth/dashboard_/research': typeof AuthDashboardResearchRoute
  '/_auth/dashboard_/screener': typeof AuthDashboardScreenerRoute
  '/_auth/dashboard_/settings': typeof AuthDashboardSettingsRoute
  '/_auth/dashboard_/strategies': typeof AuthDashboardStrategiesRoute
  '/_auth/dashboard_/tax': typeof AuthDashboardTaxRoute
  '/_auth/dashboard_/templates': typeof AuthDashboardTemplatesRoute
  '/_auth/dashboard_/watchlist': typeof AuthDashboardWatchlistRoute
  '/_auth/dashboard_/portfolios_/$portfolioId': typeof AuthDashboardPortfoliosPortfolioIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup-2fa'
    | '/sign-up'
    | '/two-factor'
    | '/verify-email'
    | '/dashboard'
    | '/dashboard/advisor'
    | '/dashboard/alerts'
    | '/dashboard/analysis'
    | '/dashboard/backtest'
    | '/dashboard/calendar'
    | '/dashboard/commodities'
    | '/dashboard/comparison'
    | '/dashboard/crypto'
    | '/dashboard/indices'
    | '/dashboard/learn-buy-sell'
    | '/dashboard/learn-fees'
    | '/dashboard/learn-investment'
    | '/dashboard/learn-rates'
    | '/dashboard/learn-ta'
    | '/dashboard/my-learning'
    | '/dashboard/news'
    | '/dashboard/portfolios'
    | '/dashboard/rates'
    | '/dashboard/research'
    | '/dashboard/screener'
    | '/dashboard/settings'
    | '/dashboard/strategies'
    | '/dashboard/tax'
    | '/dashboard/templates'
    | '/dashboard/watchlist'
    | '/dashboard/portfolios/$portfolioId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/setup-2fa'
    | '/sign-up'
    | '/two-factor'
    | '/verify-email'
    | '/dashboard'
    | '/dashboard/advisor'
    | '/dashboard/alerts'
    | '/dashboard/analysis'
    | '/dashboard/backtest'
    | '/dashboard/calendar'
    | '/dashboard/commodities'
    | '/dashboard/comparison'
    | '/dashboard/crypto'
    | '/dashboard/indices'
    | '/dashboard/learn-buy-sell'
    | '/dashboard/learn-fees'
    | '/dashboard/learn-investment'
    | '/dashboard/learn-rates'
    | '/dashboard/learn-ta'
    | '/dashboard/my-learning'
    | '/dashboard/news'
    | '/dashboard/portfolios'
    | '/dashboard/rates'
    | '/dashboard/research'
    | '/dashboard/screener'
    | '/dashboard/settings'
    | '/dashboard/strategies'
    | '/dashboard/tax'
    | '/dashboard/templates'
    | '/dashboard/watchlist'
    | '/dashboard/portfolios/$portfolioId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/setup-2fa'
    | '/sign-up'
    | '/two-factor'
    | '/verify-email'
    | '/_auth/dashboard'
    | '/_auth/dashboard_/advisor'
    | '/_auth/dashboard_/alerts'
    | '/_auth/dashboard_/analysis'
    | '/_auth/dashboard_/backtest'
    | '/_auth/dashboard_/calendar'
    | '/_auth/dashboard_/commodities'
    | '/_auth/dashboard_/comparison'
    | '/_auth/dashboard_/crypto'
    | '/_auth/dashboard_/indices'
    | '/_auth/dashboard_/learn-buy-sell'
    | '/_auth/dashboard_/learn-fees'
    | '/_auth/dashboard_/learn-investment'
    | '/_auth/dashboard_/learn-rates'
    | '/_auth/dashboard_/learn-ta'
    | '/_auth/dashboard_/my-learning'
    | '/_auth/dashboard_/news'
    | '/_auth/dashboard_/portfolios'
    | '/_auth/dashboard_/rates'
    | '/_auth/dashboard_/research'
    | '/_auth/dashboard_/screener'
    | '/_auth/dashboard_/settings'
    | '/_auth/dashboard_/strategies'
    | '/_auth/dashboard_/tax'
    | '/_auth/dashboard_/templates'
    | '/_auth/dashboard_/watchlist'
    | '/_auth/dashboard_/portfolios_/$portfolioId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  Setup2faRoute: typeof Setup2faRoute
  SignUpRoute: typeof SignUpRoute
  TwoFactorRoute: typeof TwoFactorRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/two-factor': {
      id: '/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof TwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-2fa': {
      id: '/setup-2fa'
      path: '/setup-2fa'
      fullPath: '/setup-2fa'
      preLoaderRoute: typeof Setup2faRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard_/watchlist': {
      id: '/_auth/dashboard_/watchlist'
      path: '/dashboard/watchlist'
      fullPath: '/dashboard/watchlist'
      preLoaderRoute: typeof AuthDashboardWatchlistRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard_/templates': {
      id: '/_auth/dashboard_/templates'
      path: '/dashboard/templates'
      fullPath: '/dashboard/templates'
      preLoaderRoute: typeof AuthDashboardTemplatesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard_/tax': {
      id: '/_auth/dashboard_/tax'
      path: '/dashboard/tax'
      fullPath: '/dashboard/tax'
      preLoaderRoute: typeof AuthDashboardTaxRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard_/strategies': {
      id: '/_auth/dashboard_/strategies'
      path: '/dashboard/strategies'
      fullPath: '/dashboard/strategies'
      preLoaderRoute: typeof AuthDashboardStrategiesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard_/settings': {
      id: '/_auth/dashboard_/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthDashboardSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard_/screener': {
      id: '/_auth/dashboard_/screener'
      path: '/dashboard/screener'
      fullPath: '/dashboard/screener'
      preLoaderRoute: typeof AuthDashboardScreenerRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard_/research': {
      id: '/_auth/dashboard_/research'
      path: '/dashboard/research'
      fullPath: '/dashboard/research'
      preLoaderRoute: typeof AuthDashboardResearchRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard_/rates': {
      id: '/_auth/dashboard_/rates'
      path: '/dashboard/rates'
      fullPath: '/dashboard/rates'
      preLoaderRoute: typeof AuthDashboardRatesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard_/portfolios': {
      id: '/_auth/dashboard_/portfolios'
      path: '/dashboard/portfolios'
      fullPath: '/dashboard/portfolios'
      preLoaderRoute: typeof AuthDashboardPortfoliosRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard_/news': {
      id: '/_auth/dashboard_/news'
      path: '/dashboard/news'
      fullPath: '/dashboard/news'
      preLoaderRoute: typeof AuthDashboardNewsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard_/my-learning': {
      id: '/_auth/dashboard_/my-learning'
      path: '/dashboard/my-learning'
      fullPath: '/dashboard/my-learning'
      preLoaderRoute: typeof AuthDashboardMyLearningRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard_/learn-ta': {
      id: '/_auth/dashboard_/learn-ta'
      path: '/dashboard/learn-ta'
      fullPath: '/dashboard/learn-ta'
      preLoaderRoute: typeof AuthDashboardLearnTaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard_/learn-rates': {
      id: '/_auth/dashboard_/learn-rates'
      path: '/dashboard/learn-rates'
      fullPath: '/dashboard/learn-rates'
      preLoaderRoute: typeof AuthDashboardLearnRatesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard_/learn-investment': {
      id: '/_auth/dashboard_/learn-investment'
      path: '/dashboard/learn-investment'
      fullPath: '/dashboard/learn-investment'
      preLoaderRoute: typeof AuthDashboardLearnInvestmentRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard_/learn-fees': {
      id: '/_auth/dashboard_/learn-fees'
      path: '/dashboard/learn-fees'
      fullPath: '/dashboard/learn-fees'
      preLoaderRoute: typeof AuthDashboardLearnFeesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard_/learn-buy-sell': {
      id: '/_auth/dashboard_/learn-buy-sell'
      path: '/dashboard/learn-buy-sell'
      fullPath: '/dashboard/learn-buy-sell'
      preLoaderRoute: typeof AuthDashboardLearnBuySellRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard_/indices': {
      id: '/_auth/dashboard_/indices'
      path: '/dashboard/indices'
      fullPath: '/dashboard/indices'
      preLoaderRoute: typeof AuthDashboardIndicesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard_/crypto': {
      id: '/_auth/dashboard_/crypto'
      path: '/dashboard/crypto'
      fullPath: '/dashboard/crypto'
      preLoaderRoute: typeof AuthDashboardCryptoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard_/comparison': {
      id: '/_auth/dashboard_/comparison'
      path: '/dashboard/comparison'
      fullPath: '/dashboard/comparison'
      preLoaderRoute: typeof AuthDashboardComparisonRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard_/commodities': {
      id: '/_auth/dashboard_/commodities'
      path: '/dashboard/commodities'
      fullPath: '/dashboard/commodities'
      preLoaderRoute: typeof AuthDashboardCommoditiesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard_/calendar': {
      id: '/_auth/dashboard_/calendar'
      path: '/dashboard/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof AuthDashboardCalendarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard_/backtest': {
      id: '/_auth/dashboard_/backtest'
      path: '/dashboard/backtest'
      fullPath: '/dashboard/backtest'
      preLoaderRoute: typeof AuthDashboardBacktestRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard_/analysis': {
      id: '/_auth/dashboard_/analysis'
      path: '/dashboard/analysis'
      fullPath: '/dashboard/analysis'
      preLoaderRoute: typeof AuthDashboardAnalysisRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard_/alerts': {
      id: '/_auth/dashboard_/alerts'
      path: '/dashboard/alerts'
      fullPath: '/dashboard/alerts'
      preLoaderRoute: typeof AuthDashboardAlertsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard_/advisor': {
      id: '/_auth/dashboard_/advisor'
      path: '/dashboard/advisor'
      fullPath: '/dashboard/advisor'
      preLoaderRoute: typeof AuthDashboardAdvisorRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard_/portfolios_/$portfolioId': {
      id: '/_auth/dashboard_/portfolios_/$portfolioId'
      path: '/dashboard/portfolios/$portfolioId'
      fullPath: '/dashboard/portfolios/$portfolioId'
      preLoaderRoute: typeof AuthDashboardPortfoliosPortfolioIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthDashboardAdvisorRoute: typeof AuthDashboardAdvisorRoute
  AuthDashboardAlertsRoute: typeof AuthDashboardAlertsRoute
  AuthDashboardAnalysisRoute: typeof AuthDashboardAnalysisRoute
  AuthDashboardBacktestRoute: typeof AuthDashboardBacktestRoute
  AuthDashboardCalendarRoute: typeof AuthDashboardCalendarRoute
  AuthDashboardCommoditiesRoute: typeof AuthDashboardCommoditiesRoute
  AuthDashboardComparisonRoute: typeof AuthDashboardComparisonRoute
  AuthDashboardCryptoRoute: typeof AuthDashboardCryptoRoute
  AuthDashboardIndicesRoute: typeof AuthDashboardIndicesRoute
  AuthDashboardLearnBuySellRoute: typeof AuthDashboardLearnBuySellRoute
  AuthDashboardLearnFeesRoute: typeof AuthDashboardLearnFeesRoute
  AuthDashboardLearnInvestmentRoute: typeof AuthDashboardLearnInvestmentRoute
  AuthDashboardLearnRatesRoute: typeof AuthDashboardLearnRatesRoute
  AuthDashboardLearnTaRoute: typeof AuthDashboardLearnTaRoute
  AuthDashboardMyLearningRoute: typeof AuthDashboardMyLearningRoute
  AuthDashboardNewsRoute: typeof AuthDashboardNewsRoute
  AuthDashboardPortfoliosRoute: typeof AuthDashboardPortfoliosRoute
  AuthDashboardRatesRoute: typeof AuthDashboardRatesRoute
  AuthDashboardResearchRoute: typeof AuthDashboardResearchRoute
  AuthDashboardScreenerRoute: typeof AuthDashboardScreenerRoute
  AuthDashboardSettingsRoute: typeof AuthDashboardSettingsRoute
  AuthDashboardStrategiesRoute: typeof AuthDashboardStrategiesRoute
  AuthDashboardTaxRoute: typeof AuthDashboardTaxRoute
  AuthDashboardTemplatesRoute: typeof AuthDashboardTemplatesRoute
  AuthDashboardWatchlistRoute: typeof AuthDashboardWatchlistRoute
  AuthDashboardPortfoliosPortfolioIdRoute: typeof AuthDashboardPortfoliosPortfolioIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthDashboardAdvisorRoute: AuthDashboardAdvisorRoute,
  AuthDashboardAlertsRoute: AuthDashboardAlertsRoute,
  AuthDashboardAnalysisRoute: AuthDashboardAnalysisRoute,
  AuthDashboardBacktestRoute: AuthDashboardBacktestRoute,
  AuthDashboardCalendarRoute: AuthDashboardCalendarRoute,
  AuthDashboardCommoditiesRoute: AuthDashboardCommoditiesRoute,
  AuthDashboardComparisonRoute: AuthDashboardComparisonRoute,
  AuthDashboardCryptoRoute: AuthDashboardCryptoRoute,
  AuthDashboardIndicesRoute: AuthDashboardIndicesRoute,
  AuthDashboardLearnBuySellRoute: AuthDashboardLearnBuySellRoute,
  AuthDashboardLearnFeesRoute: AuthDashboardLearnFeesRoute,
  AuthDashboardLearnInvestmentRoute: AuthDashboardLearnInvestmentRoute,
  AuthDashboardLearnRatesRoute: AuthDashboardLearnRatesRoute,
  AuthDashboardLearnTaRoute: AuthDashboardLearnTaRoute,
  AuthDashboardMyLearningRoute: AuthDashboardMyLearningRoute,
  AuthDashboardNewsRoute: AuthDashboardNewsRoute,
  AuthDashboardPortfoliosRoute: AuthDashboardPortfoliosRoute,
  AuthDashboardRatesRoute: AuthDashboardRatesRoute,
  AuthDashboardResearchRoute: AuthDashboardResearchRoute,
  AuthDashboardScreenerRoute: AuthDashboardScreenerRoute,
  AuthDashboardSettingsRoute: AuthDashboardSettingsRoute,
  AuthDashboardStrategiesRoute: AuthDashboardStrategiesRoute,
  AuthDashboardTaxRoute: AuthDashboardTaxRoute,
  AuthDashboardTemplatesRoute: AuthDashboardTemplatesRoute,
  AuthDashboardWatchlistRoute: AuthDashboardWatchlistRoute,
  AuthDashboardPortfoliosPortfolioIdRoute:
    AuthDashboardPortfoliosPortfolioIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  Setup2faRoute: Setup2faRoute,
  SignUpRoute: SignUpRoute,
  TwoFactorRoute: TwoFactorRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
