import PDFDocument from "pdfkit";

type ReportRow = {
  symbol: string;
  quantity: number;
  costBasis: number;
  lastClose: number | null;
  marketValue: number | null;
  costTotal: number;
  unrealizedAbs: number | null;
  unrealizedPct: number | null;
  weight: number | null;
  confidence: "high" | "medium" | "low" | null;
};

type ReportTotals = {
  marketValue: number;
  costTotal: number;
  unrealizedAbs: number;
  unrealizedPct: number | null;
};

export type DividendRow = {
  symbol: string;
  quantity: number;
  dividendRate: number | null;
  dividendYield: number | null;
  annualIncome: number | null;
  exDividendDate: string | null;
  dividendDate: string | null;
};

export type DividendSummary = {
  rows: DividendRow[];
  totalAnnualIncome: number;
  totalMonthlyEstimate: number;
};

export type TaxSummaryRow = {
  symbol: string;
  totalShares: number;
  acbPerShare: number;
  acbTotal: number;
  realizedGains: number;
  transactionCount: number;
};

export type TaxSummary = {
  rows: TaxSummaryRow[];
  totalRealized: number;
  taxableGains: number;
};

export type PerformanceSeries = {
  symbol: string;
  color: string;
  points: { t: number; v: number }[];
};

export type PerformanceChart = {
  range: string;
  series: PerformanceSeries[];
};

type ReportLabels = {
  marketValue: string;
  costBasis: string;
  unrealizedPL: string;
  return: string;
  holdings: string;
  allocation: string;
  performance: string;
  performanceHint: string;
  total: string;
  dividendIncome: string;
  annualIncome: string;
  monthlyEstimate: string;
  taxSummary: string;
  totalRealized: string;
  taxableGains: string;
  taxNote: string;
  noDividendData: string;
  noTransactionData: string;
  footer: string;
  colSymbol: string;
  colQty: string;
  colAvgCost: string;
  colLast: string;
  colMktValue: string;
  colCostBasis: string;
  colPL: string;
  colPLPct: string;
  colWeight: string;
  colRate: string;
  colYield: string;
  colAnnualEst: string;
  colExDate: string;
  colPayDate: string;
  colShares: string;
  colAcbPerShare: string;
  colAcbTotal: string;
  colRealized: string;
  colTxCount: string;
};

export type ReportData = {
  title: string;
  currency: string;
  asOf: string;
  rows: ReportRow[];
  totals: ReportTotals;
  locale: string;
  dividends?: DividendSummary;
  taxSummary?: TaxSummary;
  performance?: PerformanceChart;
  labels?: Partial<ReportLabels>;
};

const DEFAULT_LABELS: ReportLabels = {
  marketValue: "Market Value",
  costBasis: "Cost Basis",
  unrealizedPL: "Unrealized P/L",
  return: "Return",
  holdings: "Holdings",
  allocation: "Allocation",
  performance: "Performance",
  performanceHint: "Normalized to 100 at start of period.",
  total: "Total",
  dividendIncome: "Dividend Income",
  annualIncome: "Annual Income",
  monthlyEstimate: "Monthly Estimate",
  taxSummary: "Tax Summary",
  totalRealized: "Total Realized Gains",
  taxableGains: "Taxable Gains (50%)",
  taxNote: "50% inclusion rate — consult a tax advisor.",
  noDividendData: "No dividend-paying holdings.",
  noTransactionData: "No transactions recorded.",
  footer: "Generated by FinaTalk. This report is for informational purposes only and does not constitute investment advice.",
  colSymbol: "Symbol",
  colQty: "Qty",
  colAvgCost: "Avg Cost",
  colLast: "Last",
  colMktValue: "Mkt Value",
  colCostBasis: "Cost Basis",
  colPL: "P/L",
  colPLPct: "P/L %",
  colWeight: "Weight",
  colRate: "Rate",
  colYield: "Yield",
  colAnnualEst: "Annual Est.",
  colExDate: "Ex-Date",
  colPayDate: "Pay Date",
  colShares: "Shares",
  colAcbPerShare: "ACB/Share",
  colAcbTotal: "ACB Total",
  colRealized: "Realized G/L",
  colTxCount: "Txs",
};

function fmtCur(value: number, currency: string): string {
  try {
    return new Intl.NumberFormat("en-US", {
      style: "currency",
      currency,
      maximumFractionDigits: 2,
    }).format(value);
  } catch {
    return `${currency} ${value.toFixed(2)}`;
  }
}

function fmtPct(value: number | null): string {
  if (value == null || !Number.isFinite(value)) return "—";
  const sign = value > 0 ? "+" : "";
  return `${sign}${value.toFixed(2)}%`;
}

function fmtQty(q: number): string {
  return q.toLocaleString("en-US", { maximumFractionDigits: 4 });
}

const HEADER_BG = "#dbeafe";
const HEADER_FG = "#1e293b";
const ROW_ALT = "#f8fafc";
const GREEN = "#10b981";
const RED = "#ef4444";
const GRAY = "#64748b";
const BORDER = "#e2e8f0";

export function generatePortfolioReport(data: ReportData): Promise<Buffer> {
  const L: ReportLabels = { ...DEFAULT_LABELS, ...(data.labels ?? {}) };
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "LETTER",
      margin: 40,
      info: {
        Title: `${data.title} — Portfolio Report`,
        Author: "FinaTalk",
        Subject: "Portfolio Report",
      },
    });

    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const pageW = doc.page.width - doc.page.margins.left - doc.page.margins.right;

    // ── Header ───────────────────────────────────────────────────
    doc
      .fontSize(22)
      .font("Helvetica-Bold")
      .fillColor("#0f172a")
      .text(data.title, { align: "left" });
    doc
      .fontSize(10)
      .font("Helvetica")
      .fillColor(GRAY)
      .text(`Portfolio Report · ${data.currency} · ${data.asOf}`, {
        align: "left",
      });
    doc.moveDown(0.5);
    doc
      .strokeColor(BORDER)
      .lineWidth(1)
      .moveTo(doc.x, doc.y)
      .lineTo(doc.x + pageW, doc.y)
      .stroke();
    doc.moveDown(0.8);

    // ── Summary Cards ────────────────────────────────────────────
    const cardW = pageW / 4;
    const cardY = doc.y;
    const cards = [
      {
        label: L.marketValue,
        value: fmtCur(data.totals.marketValue, data.currency),
        color: "#0f172a",
      },
      {
        label: L.costBasis,
        value: fmtCur(data.totals.costTotal, data.currency),
        color: "#0f172a",
      },
      {
        label: L.unrealizedPL,
        value: fmtCur(data.totals.unrealizedAbs, data.currency),
        color: data.totals.unrealizedAbs >= 0 ? GREEN : RED,
      },
      {
        label: L.return,
        value: fmtPct(data.totals.unrealizedPct),
        color:
          data.totals.unrealizedPct != null && data.totals.unrealizedPct >= 0
            ? GREEN
            : RED,
      },
    ];

    for (let i = 0; i < cards.length; i++) {
      const x = doc.page.margins.left + i * cardW;
      doc
        .fontSize(8)
        .font("Helvetica")
        .fillColor(GRAY)
        .text(cards[i]!.label, x, cardY, { width: cardW - 8 });
      doc
        .fontSize(14)
        .font("Helvetica-Bold")
        .fillColor(cards[i]!.color)
        .text(cards[i]!.value, x, cardY + 12, { width: cardW - 8 });
    }

    doc.y = cardY + 36;
    doc.moveDown(1);

    // ── Holdings Table ───────────────────────────────────────────
    doc
      .fontSize(12)
      .font("Helvetica-Bold")
      .fillColor("#0f172a")
      .text(L.holdings, doc.page.margins.left, doc.y, { width: pageW });
    doc.moveDown(0.5);

    const colRatios = [10, 8, 11, 11, 13, 13, 12, 10, 12];
    const ratioSum = colRatios.reduce((a, b) => a + b, 0);
    const cols = [
      { label: L.colSymbol, align: "left" as const },
      { label: L.colQty, align: "right" as const },
      { label: L.colAvgCost, align: "right" as const },
      { label: L.colLast, align: "right" as const },
      { label: L.colMktValue, align: "right" as const },
      { label: L.colCostBasis, align: "right" as const },
      { label: L.colPL, align: "right" as const },
      { label: L.colPLPct, align: "right" as const },
      { label: L.colWeight, align: "right" as const },
    ].map((c, i) => ({ ...c, width: Math.floor((colRatios[i]! / ratioSum) * pageW) }));
    const remainder = pageW - cols.reduce((s, c) => s + c.width, 0);
    cols[cols.length - 1]!.width += remainder;

    const tableX = doc.page.margins.left;
    const rowH = 18;

    function drawHeaderRow(y: number) {
      doc.rect(tableX, y, pageW, rowH).fill(HEADER_BG);
      let cx = tableX + 4;
      for (const col of cols) {
        doc
          .fontSize(7)
          .font("Helvetica-Bold")
          .fillColor(HEADER_FG);
        if (col.align === "right") {
          doc.text(col.label, cx, y + 5, {
            width: col.width - 8,
            align: "right",
          });
        } else {
          doc.text(col.label, cx, y + 5, { width: col.width - 8 });
        }
        cx += col.width;
      }
      return y + rowH;
    }

    function drawDataRow(row: ReportRow, y: number, alt: boolean) {
      if (alt) {
        doc.rect(tableX, y, pageW, rowH).fill(ROW_ALT);
      }
      let cx = tableX + 4;
      const values = [
        row.symbol,
        fmtQty(row.quantity),
        fmtCur(row.costBasis, data.currency),
        row.lastClose != null ? fmtCur(row.lastClose, data.currency) : "—",
        row.marketValue != null ? fmtCur(row.marketValue, data.currency) : "—",
        fmtCur(row.costTotal, data.currency),
        row.unrealizedAbs != null
          ? fmtCur(row.unrealizedAbs, data.currency)
          : "—",
        fmtPct(row.unrealizedPct),
        row.weight != null ? `${row.weight.toFixed(1)}%` : "—",
      ];
      for (let i = 0; i < cols.length; i++) {
        const col = cols[i]!;
        let color = "#0f172a";
        if (i === 6 && row.unrealizedAbs != null) {
          color = row.unrealizedAbs >= 0 ? GREEN : RED;
        }
        if (i === 7 && row.unrealizedPct != null) {
          color = row.unrealizedPct >= 0 ? GREEN : RED;
        }
        doc.fontSize(7).font(i === 0 ? "Helvetica-Bold" : "Helvetica").fillColor(color);
        if (col.align === "right") {
          doc.text(values[i]!, cx, y + 5, {
            width: col.width - 8,
            align: "right",
          });
        } else {
          doc.text(values[i]!, cx, y + 5, { width: col.width - 8 });
        }
        cx += col.width;
      }
      return y + rowH;
    }

    let ty = drawHeaderRow(doc.y);

    for (let i = 0; i < data.rows.length; i++) {
      if (ty + rowH > doc.page.height - doc.page.margins.bottom - 30) {
        doc.addPage();
        ty = drawHeaderRow(doc.page.margins.top);
      }
      ty = drawDataRow(data.rows[i]!, ty, i % 2 === 1);
    }

    // Totals row
    if (ty + rowH > doc.page.height - doc.page.margins.bottom - 30) {
      doc.addPage();
      ty = drawHeaderRow(doc.page.margins.top);
    }
    doc.rect(tableX, ty, pageW, rowH).fill("#e2e8f0");
    let cx = tableX + 4;
    const totalValues = [
      L.total,
      "",
      "",
      "",
      fmtCur(data.totals.marketValue, data.currency),
      fmtCur(data.totals.costTotal, data.currency),
      fmtCur(data.totals.unrealizedAbs, data.currency),
      fmtPct(data.totals.unrealizedPct),
      "100%",
    ];
    for (let i = 0; i < cols.length; i++) {
      const col = cols[i]!;
      let color = "#0f172a";
      if (i === 6) color = data.totals.unrealizedAbs >= 0 ? GREEN : RED;
      if (i === 7 && data.totals.unrealizedPct != null)
        color = data.totals.unrealizedPct >= 0 ? GREEN : RED;
      doc.fontSize(7).font("Helvetica-Bold").fillColor(color);
      if (col.align === "right") {
        doc.text(totalValues[i]!, cx, ty + 5, {
          width: col.width - 8,
          align: "right",
        });
      } else {
        doc.text(totalValues[i]!, cx, ty + 5, { width: col.width - 8 });
      }
      cx += col.width;
    }
    ty += rowH;

    // ── Performance Chart ────────────────────────────────────────
    if (data.performance && data.performance.series.some((s) => s.points.length >= 2)) {
      const chartH = 180;
      const legendLineH = 12;
      const activeSeries = data.performance.series.filter((s) => s.points.length >= 2);
      const legendRows = Math.ceil(activeSeries.length / 4);
      const sectionH = 22 + chartH + 10 + legendRows * legendLineH + 12;

      let py = ty + 16;
      if (py + sectionH > doc.page.height - doc.page.margins.bottom - 40) {
        doc.addPage();
        py = doc.page.margins.top;
      }

      doc
        .fontSize(12)
        .font("Helvetica-Bold")
        .fillColor("#0f172a")
        .text(`${L.performance} · ${data.performance.range}`, tableX, py, {
          width: pageW,
        });
      py += 20;

      const plotX = tableX + 36;
      const plotY = py;
      const plotW = pageW - 36 - 8;
      const plotH = chartH;

      let tMin = Infinity;
      let tMax = -Infinity;
      let vMin = Infinity;
      let vMax = -Infinity;
      for (const s of activeSeries) {
        for (const p of s.points) {
          if (p.t < tMin) tMin = p.t;
          if (p.t > tMax) tMax = p.t;
          if (p.v < vMin) vMin = p.v;
          if (p.v > vMax) vMax = p.v;
        }
      }
      if (tMin === tMax) tMax = tMin + 1;
      if (vMin === vMax) {
        vMin -= 1;
        vMax += 1;
      } else {
        const pad = (vMax - vMin) * 0.08;
        vMin -= pad;
        vMax += pad;
      }

      const xFor = (t: number) => plotX + ((t - tMin) / (tMax - tMin)) * plotW;
      const yFor = (v: number) => plotY + plotH - ((v - vMin) / (vMax - vMin)) * plotH;

      // Grid + y-axis labels (5 horizontal lines)
      doc.save();
      doc.strokeColor(BORDER).lineWidth(0.5);
      for (let g = 0; g <= 4; g++) {
        const gy = plotY + (plotH / 4) * g;
        doc.moveTo(plotX, gy).lineTo(plotX + plotW, gy).stroke();
        const gv = vMax - ((vMax - vMin) / 4) * g;
        doc
          .fontSize(6)
          .font("Helvetica")
          .fillColor(GRAY)
          .text(gv.toFixed(0), tableX, gy - 3, { width: 32, align: "right" });
      }
      doc.restore();

      // Baseline at v=100 (the normalization base)
      if (100 >= vMin && 100 <= vMax) {
        doc.save();
        doc.strokeColor("#94a3b8").lineWidth(0.5).dash(2, { space: 2 });
        const by = yFor(100);
        doc.moveTo(plotX, by).lineTo(plotX + plotW, by).stroke();
        doc.undash();
        doc.restore();
      }

      // Series polylines
      for (const s of activeSeries) {
        if (s.points.length < 2) continue;
        doc.save();
        doc.strokeColor(s.color).lineWidth(1.2);
        const first = s.points[0]!;
        doc.moveTo(xFor(first.t), yFor(first.v));
        for (let i = 1; i < s.points.length; i++) {
          const p = s.points[i]!;
          doc.lineTo(xFor(p.t), yFor(p.v));
        }
        doc.stroke();
        doc.restore();
      }

      // Plot border
      doc.save();
      doc.strokeColor(BORDER).lineWidth(0.5);
      doc.rect(plotX, plotY, plotW, plotH).stroke();
      doc.restore();

      py = plotY + plotH + 10;

      // Legend — flow items across the row, wrap to next row when full
      const ITEM_GAP = 14;
      const SWATCH_W = 10;
      const SWATCH_SYMBOL_GAP = 4;
      const SYMBOL_PCT_GAP = 4;
      let lx = tableX;
      let ly = py;
      let legendRowCount = 1;
      for (const s of activeSeries) {
        const last = s.points[s.points.length - 1]!.v;
        const delta = last - 100;
        const pctStr = `${delta >= 0 ? "+" : ""}${delta.toFixed(2)}%`;
        const color = delta >= 0 ? GREEN : RED;

        doc.fontSize(7).font("Helvetica-Bold");
        const symbolW = doc.widthOfString(s.symbol);
        doc.font("Helvetica");
        const pctW = doc.widthOfString(pctStr);
        const itemW = SWATCH_W + SWATCH_SYMBOL_GAP + symbolW + SYMBOL_PCT_GAP + pctW;

        if (lx !== tableX && lx + itemW > tableX + pageW) {
          lx = tableX;
          ly += legendLineH;
          legendRowCount++;
        }

        doc.save();
        doc.rect(lx, ly + 2, SWATCH_W, 3).fill(s.color);
        doc.restore();

        doc
          .fontSize(7)
          .font("Helvetica-Bold")
          .fillColor("#0f172a")
          .text(s.symbol, lx + SWATCH_W + SWATCH_SYMBOL_GAP, ly, { lineBreak: false });

        doc
          .fontSize(7)
          .font("Helvetica")
          .fillColor(color)
          .text(
            pctStr,
            lx + SWATCH_W + SWATCH_SYMBOL_GAP + symbolW + SYMBOL_PCT_GAP,
            ly,
            { lineBreak: false },
          );

        lx += itemW + ITEM_GAP;
      }
      py += legendRowCount * legendLineH + 4;

      doc
        .fontSize(7)
        .font("Helvetica-Oblique")
        .fillColor(GRAY)
        .text(L.performanceHint, tableX, py, { width: pageW });
      py += 12;

      ty = py;
    }

    // ── Allocation ───────────────────────────────────────────────
    const withValue = data.rows.filter(
      (r) => r.marketValue != null && r.marketValue > 0,
    );
    if (withValue.length > 0) {
      const COLORS = [
        "#3b82f6", "#10b981", "#f59e0b", "#ef4444",
        "#8b5cf6", "#ec4899", "#14b8a6", "#f97316",
        "#06b6d4", "#84cc16", "#e11d48", "#7c3aed",
      ];

      const outerR = 55;
      const innerR = 30;
      const donutDiameter = outerR * 2;
      const legendRowH = 15;
      const legendH = withValue.length * legendRowH;
      const sectionH = Math.max(donutDiameter, legendH) + 30;

      let ay = ty + 20;
      if (ay + sectionH > doc.page.height - doc.page.margins.bottom - 40) {
        doc.addPage();
        ay = doc.page.margins.top;
      }

      doc
        .fontSize(12)
        .font("Helvetica-Bold")
        .fillColor("#0f172a")
        .text(L.allocation, tableX, ay, { width: pageW });
      ay += 22;

      const donutCx = tableX + outerR + 10;
      const donutCy = ay + outerR;
      let angle = -Math.PI / 2;

      for (let i = 0; i < withValue.length; i++) {
        const slice = (withValue[i]!.weight! / 100) * Math.PI * 2;
        if (slice <= 0) continue;
        const endAngle = angle + slice;
        const large = slice > Math.PI ? 1 : 0;

        const ox1 = donutCx + outerR * Math.cos(angle);
        const oy1 = donutCy + outerR * Math.sin(angle);
        const ox2 = donutCx + outerR * Math.cos(endAngle);
        const oy2 = donutCy + outerR * Math.sin(endAngle);
        const ix2 = donutCx + innerR * Math.cos(endAngle);
        const iy2 = donutCy + innerR * Math.sin(endAngle);
        const ix1 = donutCx + innerR * Math.cos(angle);
        const iy1 = donutCy + innerR * Math.sin(angle);

        doc.save();
        doc
          .path(
            `M ${ox1} ${oy1} A ${outerR} ${outerR} 0 ${large} 1 ${ox2} ${oy2}` +
            ` L ${ix2} ${iy2} A ${innerR} ${innerR} 0 ${large} 0 ${ix1} ${iy1} Z`,
          )
          .fill(COLORS[i % COLORS.length]!);
        doc.restore();

        angle = endAngle;
      }

      const legendX = tableX + donutDiameter + 40;
      const legendTop = donutCy - legendH / 2;
      for (let i = 0; i < withValue.length; i++) {
        const r = withValue[i]!;
        const ly = legendTop + i * legendRowH;
        doc.save();
        doc.rect(legendX, ly + 1, 8, 8).fill(COLORS[i % COLORS.length]!);
        doc.restore();
        doc
          .font("Helvetica")
          .fontSize(7)
          .fillColor("#0f172a");
        const label = `${r.symbol}  ${fmtCur(r.marketValue ?? 0, data.currency)}  (${r.weight!.toFixed(1)}%)`;
        doc.text(label, legendX + 14, ly + 2, { lineBreak: false });
      }

      ay = donutCy + outerR + 10;
      doc.x = tableX;
      doc.y = ay;
    } else {
      doc.x = tableX;
      doc.y = ty + 20;
    }

    // ── Dividend Income ──────────────────────────────────────────
    if (data.dividends) {
      const divRows = data.dividends.rows.filter(
        (r) => r.annualIncome != null && r.annualIncome > 0,
      );
      const divColRatios = [14, 12, 12, 12, 16, 17, 17];
      const divRatioSum = divColRatios.reduce((a, b) => a + b, 0);
      const divCols = [
        { label: L.colSymbol, align: "left" as const },
        { label: L.colQty, align: "right" as const },
        { label: L.colRate, align: "right" as const },
        { label: L.colYield, align: "right" as const },
        { label: L.colAnnualEst, align: "right" as const },
        { label: L.colExDate, align: "left" as const },
        { label: L.colPayDate, align: "left" as const },
      ].map((c, i) => ({
        ...c,
        width: Math.floor((divColRatios[i]! / divRatioSum) * pageW),
      }));
      const divRemainder = pageW - divCols.reduce((s, c) => s + c.width, 0);
      divCols[divCols.length - 1]!.width += divRemainder;

      const headerLines = 2;
      const summaryH = 34;
      const tableH =
        rowH + Math.max(divRows.length, 1) * rowH + rowH;
      const sectionH = 22 + summaryH + tableH + headerLines;

      let dy = doc.y + 10;
      if (dy + sectionH > doc.page.height - doc.page.margins.bottom - 40) {
        doc.addPage();
        dy = doc.page.margins.top;
      }

      doc
        .fontSize(12)
        .font("Helvetica-Bold")
        .fillColor("#0f172a")
        .text(L.dividendIncome, tableX, dy, { width: pageW });
      dy += 20;

      // Summary: Annual + Monthly
      const halfW = pageW / 2;
      doc
        .fontSize(8)
        .font("Helvetica")
        .fillColor(GRAY)
        .text(L.annualIncome, tableX, dy, { width: halfW - 8 });
      doc
        .fontSize(8)
        .font("Helvetica")
        .fillColor(GRAY)
        .text(L.monthlyEstimate, tableX + halfW, dy, { width: halfW - 8 });
      doc
        .fontSize(13)
        .font("Helvetica-Bold")
        .fillColor("#0f172a")
        .text(
          fmtCur(data.dividends.totalAnnualIncome, data.currency),
          tableX,
          dy + 11,
          { width: halfW - 8 },
        );
      doc
        .fontSize(13)
        .font("Helvetica-Bold")
        .fillColor("#0f172a")
        .text(
          fmtCur(data.dividends.totalMonthlyEstimate, data.currency),
          tableX + halfW,
          dy + 11,
          { width: halfW - 8 },
        );
      dy += 34;

      // Dividend table
      function drawDivHeader(y: number) {
        doc.rect(tableX, y, pageW, rowH).fill(HEADER_BG);
        let hx = tableX + 4;
        for (const col of divCols) {
          doc.fontSize(7).font("Helvetica-Bold").fillColor(HEADER_FG);
          doc.text(col.label, hx, y + 5, {
            width: col.width - 8,
            align: col.align,
          });
          hx += col.width;
        }
        return y + rowH;
      }

      dy = drawDivHeader(dy);

      if (divRows.length === 0) {
        doc.rect(tableX, dy, pageW, rowH).fill(ROW_ALT);
        doc
          .fontSize(8)
          .font("Helvetica")
          .fillColor(GRAY)
          .text(L.noDividendData, tableX + 4, dy + 5, {
            width: pageW - 8,
            align: "center",
          });
        dy += rowH;
      } else {
        for (let i = 0; i < divRows.length; i++) {
          if (dy + rowH > doc.page.height - doc.page.margins.bottom - 30) {
            doc.addPage();
            dy = drawDivHeader(doc.page.margins.top);
          }
          const r = divRows[i]!;
          if (i % 2 === 1) doc.rect(tableX, dy, pageW, rowH).fill(ROW_ALT);
          const vals = [
            r.symbol,
            fmtQty(r.quantity),
            r.dividendRate != null ? fmtCur(r.dividendRate, data.currency) : "—",
            r.dividendYield != null ? `${(r.dividendYield * 100).toFixed(2)}%` : "—",
            r.annualIncome != null ? fmtCur(r.annualIncome, data.currency) : "—",
            r.exDividendDate ?? "—",
            r.dividendDate ?? "—",
          ];
          let vx = tableX + 4;
          for (let c = 0; c < divCols.length; c++) {
            const col = divCols[c]!;
            doc
              .fontSize(7)
              .font(c === 0 ? "Helvetica-Bold" : "Helvetica")
              .fillColor("#0f172a");
            doc.text(vals[c]!, vx, dy + 5, {
              width: col.width - 8,
              align: col.align,
            });
            vx += col.width;
          }
          dy += rowH;
        }
      }

      doc.x = tableX;
      doc.y = dy;
    }

    // ── Tax Summary ──────────────────────────────────────────────
    if (data.taxSummary) {
      const txRows = data.taxSummary.rows;
      const taxColRatios = [14, 12, 14, 16, 16, 10];
      const taxRatioSum = taxColRatios.reduce((a, b) => a + b, 0);
      const taxCols = [
        { label: L.colSymbol, align: "left" as const },
        { label: L.colShares, align: "right" as const },
        { label: L.colAcbPerShare, align: "right" as const },
        { label: L.colAcbTotal, align: "right" as const },
        { label: L.colRealized, align: "right" as const },
        { label: L.colTxCount, align: "right" as const },
      ].map((c, i) => ({
        ...c,
        width: Math.floor((taxColRatios[i]! / taxRatioSum) * pageW),
      }));
      const taxRemainder = pageW - taxCols.reduce((s, c) => s + c.width, 0);
      taxCols[taxCols.length - 1]!.width += taxRemainder;

      const summaryH = 34;
      const tableH = rowH + Math.max(txRows.length, 1) * rowH;
      const sectionH = 22 + summaryH + tableH + 20;

      let sy = doc.y + 14;
      if (sy + sectionH > doc.page.height - doc.page.margins.bottom - 40) {
        doc.addPage();
        sy = doc.page.margins.top;
      }

      doc
        .fontSize(12)
        .font("Helvetica-Bold")
        .fillColor("#0f172a")
        .text(L.taxSummary, tableX, sy, { width: pageW });
      sy += 20;

      // Summary: Total realized + Taxable gains
      const halfW = pageW / 2;
      doc
        .fontSize(8)
        .font("Helvetica")
        .fillColor(GRAY)
        .text(L.totalRealized, tableX, sy, { width: halfW - 8 });
      doc
        .fontSize(8)
        .font("Helvetica")
        .fillColor(GRAY)
        .text(L.taxableGains, tableX + halfW, sy, { width: halfW - 8 });
      doc
        .fontSize(13)
        .font("Helvetica-Bold")
        .fillColor(data.taxSummary.totalRealized >= 0 ? GREEN : RED)
        .text(
          fmtCur(data.taxSummary.totalRealized, data.currency),
          tableX,
          sy + 11,
          { width: halfW - 8 },
        );
      doc
        .fontSize(13)
        .font("Helvetica-Bold")
        .fillColor("#0f172a")
        .text(
          fmtCur(data.taxSummary.taxableGains, data.currency),
          tableX + halfW,
          sy + 11,
          { width: halfW - 8 },
        );
      sy += 34;

      // Tax table
      function drawTaxHeader(y: number) {
        doc.rect(tableX, y, pageW, rowH).fill(HEADER_BG);
        let hx = tableX + 4;
        for (const col of taxCols) {
          doc.fontSize(7).font("Helvetica-Bold").fillColor(HEADER_FG);
          doc.text(col.label, hx, y + 5, {
            width: col.width - 8,
            align: col.align,
          });
          hx += col.width;
        }
        return y + rowH;
      }

      sy = drawTaxHeader(sy);

      if (txRows.length === 0) {
        doc.rect(tableX, sy, pageW, rowH).fill(ROW_ALT);
        doc
          .fontSize(8)
          .font("Helvetica")
          .fillColor(GRAY)
          .text(L.noTransactionData, tableX + 4, sy + 5, {
            width: pageW - 8,
            align: "center",
          });
        sy += rowH;
      } else {
        for (let i = 0; i < txRows.length; i++) {
          if (sy + rowH > doc.page.height - doc.page.margins.bottom - 30) {
            doc.addPage();
            sy = drawTaxHeader(doc.page.margins.top);
          }
          const r = txRows[i]!;
          if (i % 2 === 1) doc.rect(tableX, sy, pageW, rowH).fill(ROW_ALT);
          const vals = [
            r.symbol,
            fmtQty(r.totalShares),
            fmtCur(r.acbPerShare, data.currency),
            fmtCur(r.acbTotal, data.currency),
            fmtCur(r.realizedGains, data.currency),
            String(r.transactionCount),
          ];
          let vx = tableX + 4;
          for (let c = 0; c < taxCols.length; c++) {
            const col = taxCols[c]!;
            let color = "#0f172a";
            if (c === 4) color = r.realizedGains >= 0 ? GREEN : RED;
            doc
              .fontSize(7)
              .font(c === 0 ? "Helvetica-Bold" : "Helvetica")
              .fillColor(color);
            doc.text(vals[c]!, vx, sy + 5, {
              width: col.width - 8,
              align: col.align,
            });
            vx += col.width;
          }
          sy += rowH;
        }
      }

      doc
        .fontSize(7)
        .font("Helvetica-Oblique")
        .fillColor(GRAY)
        .text(L.taxNote, tableX, sy + 4, { width: pageW });
      doc.x = tableX;
      doc.y = sy + 16;
    }

    // ── Footer ───────────────────────────────────────────────────
    doc.moveDown(1.5);
    doc
      .fontSize(7)
      .font("Helvetica")
      .fillColor(GRAY)
      .text(L.footer, tableX, doc.y, { width: pageW, align: "center" });

    doc.end();
  });
}
